#!/usr/bin/python

import sys
import csv
import json

infname = sys.argv[1]
outfname = sys.argv[2]

j = json.load(open(infname))
w = csv.writer(open(outfname, 'w'), quoting=csv.QUOTE_NONNUMERIC)

w.writerow(('start', 'end', 'person', 'text'))

for a in j['annotations']:
    w.writerow((
        float(a['begin']) / 1000,
        float(a['end']) / 1000,
        a['parsed']['person'],
        a['parsed']['text'].encode('utf-8'),
    ))
